Use GD1C2021;
GO

--drop table ESTUDIANTES_CON_INSOMNIO.ClienteTemp;
--DROP TABLE ESTUDIANTES_CON_INSOMNIO.CompraTemp;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.CompraPC;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.CompraAccesorio;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.ItemPC;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.ItemAccesorio;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Accesorio;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Compra;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Factura;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Cliente;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Sucursal;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.PC;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.PlacaVideo;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.DiscoRigido;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Microprocesador;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.MemoriaRAM;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Fabricante;

drop schema ESTUDIANTES_CON_INSOMNIO;