Use GD1C2021;
GO

drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.CompraPC;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.CompraAccesorio;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.ItemPC;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.ItemAccesorio;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Accesorio;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Compra;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Factura;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Cliente;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Sucursal;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.PC;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.PlacaVideo;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.DiscoRigido;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Microprocesador;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.MemoriaRAM;
drop table GD1C2021.ESTUDIANTES_CON_INSOMNIO.Fabricante;

drop view ESTUDIANTES_CON_INSOMNIO.vistaAccesorio;
drop view ESTUDIANTES_CON_INSOMNIO.vistaCliente;
drop view ESTUDIANTES_CON_INSOMNIO.vistaCompra;
drop view ESTUDIANTES_CON_INSOMNIO.vistaCompraAccesorio;
drop view ESTUDIANTES_CON_INSOMNIO.vistaCompraPC;
drop view ESTUDIANTES_CON_INSOMNIO.vistaDiscoRigido;
drop view ESTUDIANTES_CON_INSOMNIO.vistaFabricante;
drop view ESTUDIANTES_CON_INSOMNIO.vistaFactura;
drop view ESTUDIANTES_CON_INSOMNIO.vistaItemAccesorio;
drop view ESTUDIANTES_CON_INSOMNIO.vistaItemPC;
drop view ESTUDIANTES_CON_INSOMNIO.vistaMemoriaRAM;
drop view ESTUDIANTES_CON_INSOMNIO.vistaMicroprocesador;
drop view ESTUDIANTES_CON_INSOMNIO.vistaPC;
drop view ESTUDIANTES_CON_INSOMNIO.vistaPlacaVideo;
drop view ESTUDIANTES_CON_INSOMNIO.vistaSucursal;

drop schema ESTUDIANTES_CON_INSOMNIO;